name: CD Pipeline
on: push

jobs:
  deployment:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install helm
        uses: azure/setup-helm@v3

      - name: Validate helm chart
        shell: bash
        run: |
          helm lint .helm/ --values .helm/values.azure.yaml
